#!/bin/zsh
# shellcheck disable=SC2154,SC2086

MY_PATH=${0:A:h}

DEPS=(menu_zsh turbo_zsh)

info() {
    printf "\e[93;44;1m Ω \033[97;22m%s\033[K\033[0m\n" "$1"
}
info "SETUP"
source ${MY_PATH}/banner.zsh

info "Checking dependencies..."

for folder in "${DEPS[@]}"; do
  if [[ ! -d "${MY_PATH}/${folder}" ]]; then
    info "Linking ${folder}"
    git clone "https://github.com/juliandicks/${folder}.git"
  fi
done

info "Done."
