#!/bin/zsh

: "${OHM_PATH:?OHM_PATH is not set. Source init.zsh first.}"; source "${OHM_PATH}/init_lib.zsh" || { print -u2 -- "Failed to source ${OHM_PATH}/init_lib.zsh"; exit 1; }

uses crt_lib.zsh
uses spinner_lib.zsh

pretty_print() {
	local tHDR="$Black;$(AsBg BrightWhite)"
  local tDLG="$BrightWhite;$(AsBg Blue)"
  local tFLD="$BrightYellow"
  local bg=$(AsBg $TextAttrBg)
  local tDLGB="$BrightWhite;$bg"
	CursorOff

	printf "\e[%sm\n   \e[%sm ≡         Configure Spinner            \e[0m\n" ${bg} $tHDR
	printf "\e[%sm   \e[%sm▌┌────────────────────────────────────┐▐\e[0m\n" ${bg} $tDLG
	printf "\e[%sm   \e[%sm▌│  SPINNER_FA1                       │▐\e[0m\n" ${bg} $tDLG
	printf "\e[%sm   \e[%sm▌└────────────────────────────────────┘▐\e[0m\n" ${bg} $tDLG
	printf "\e[%sm   \e[%sm▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀\e[0m\n" ${bg} $tDLGB

	CursorOn

	# Dialog OptionsArray onChange onSelect onClose

}

pretty_print
